name: Update Matrix Docker Ansible Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Update Matrix Docker Ansible Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_ADDRESS }}
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd matrix-docker-ansible-deploy
            # Update the repo
            git stash
            git pull
            git stash pop
            # Reinstall galaxy roles
            rm -rf roles/galaxy
            ansible-galaxy install -r requirements.yml -p roles/galaxy/ --force
            # Configure the vault password and run the playbook
            echo "${{ secrets.VAULT_PASS_PROD }}" | ansible-playbook -i inventory/hosts_local setup.yml --tags=setup-all,ensure-matrix-users-created,start --vault-password-file=/bin/cat
